### ISSUE TITLE
Unable to create projects in (nested) subgroup

### ISSUE THREAD

**Issue by syphernl** [zaquestion/lab#782] opened 2022-02-03 09:01 UTC
I'm trying to create a bunch of projects in a nested subgroup, which according to #450 should work. 

In my case it however errors out:
```sh
❯ lab project create org/tools/components/foo
2022/02/03 09:58:24 ERROR: project_create.go:57: Group 'org/tools/components' not found
```

The `org/tools/components` subgroup exists.

**Comment by bmeneg** [comment] 2022-02-03 13:27
Hi @syphernl,

Are you sure your user has write access in the group-level so you can create a new project there?
You must have at least `developer` role and your API token also must have been created with the `api` access checkbox set.

**Comment by syphernl** [comment] 2022-02-03 13:33
Hi @bmeneg,

Creating projects in the webui works just fine. The token is scoped to `api` and offers `owner` permissions in the Gitlab Group. Should be enough ;-)

I have just tried with a fresh token (which uses the `glpat` prefix) but that one fails as well.

**Comment by bmeneg** [comment] 2022-02-03 14:40
Ok. That's odd.
Even though I can't reproduce the failure we (I pinged @zampierilucas to help) found something odd in the code indeed.
As soon as I have something I'll open an PR and ask you to test.

**Comment by bmeneg** [comment] 2022-02-03 20:37
@syphernl would you mind testing the PR #784 changes in your environment ?

**Comment by syphernl** [comment] 2022-02-07 12:57
> @syphernl would you mind testing the PR #784 changes in your environment ?

@bmeneg I have tested it, it does a bit more than before but I wasn't able to create a project with it just yet.

```
❯ ./lab --version
lab version v0.23.0-56-gb25dc45

❯ ./lab project create org/tools/foo
2022/02/07 13:51:49 ERROR: project_create.go:57: found multiple groups with the same name:
	org/tools/containers
	org/tools/pre-commit-hooks
	org/tools/terraform-aws-components
	org/tools/terraform-modules
	org/tools
use one of the above path options
```

**Comment by bmeneg** [comment] 2022-02-07 13:06
Hmm, ok. That's indeed broken.
Let me check it again.

**Comment by bmeneg** [comment] 2022-02-07 15:39
@syphernl ok, can you test it again?

Just a note for the error about `remote origin already exists.`: it happened because you created the project from within a repo dir and lab tried to create an "origin" remote to refer to the newly created project. I added a commit in the PR to remove this _default_ behavior, now, if you really want to create a remote pointing to the new project you can pass the `--remote <name>` flag to the `lab project create` call.

**Comment by syphernl** [comment] 2022-02-08 07:08
@bmeneg Now I'm getting an error that the group doesn't exist:

```sh
❯ ./lab/lab --version
lab version v0.23.0-57-gb2db304

❯ lab project create org/tools/foo
2022/02/08 08:06:33 ERROR: project_create.go:57: Group 'org/tools' not found
```

**Comment by syphernl** [comment] 2022-02-09 07:30
@bmeneg Seems to be working fine now! 👍🏻 
```
❯ ./lab/lab --version
lab version v0.23.0-57-gce14486

❯ ./lab/lab project create org/tools/foo
https://gitlab.com/org/tools/foo
```

**Comment by bmeneg** [comment] 2022-02-09 10:33
Closing this issue based on @syphernl feedback and MR review.

Many thanks.

**Closed by bmeneg** 2022-02-09 10:33 UTC

**Comment by syphernl** [comment] 2022-02-09 10:39
Thanks for your quick help & fix @bmeneg !
