### ISSUE TITLE
Namespace support for project creation

### ISSUE THREAD

**Issue by DubKF** [zaquestion/lab#445] opened 2020-10-01 02:01 UTC
Hi,
We are using namespaces and that's the reason I can't use lab at the moment as there is no way to pass on the parameter to the API. However it seems the git client the project relies on under the hood supports the [NamespaceId attribute](https://github.com/xanzy/go-gitlab/blob/master/projects.go#L468)

Would it be possible to support the extra attribute? 

This would help with cases like mine, where I just have developer permissions for  namespace and can't use the automatic project creation via pushing to a not yet existing remote (this would set wrongly set [the visibility to "private"](https://stackoverflow.com/questions/57395399/gitlab-default-project-visibility-when-creating-projects-from-terminal) instead of "internal")

**Comment by zaquestion** [comment] 2020-10-01 16:00
Dupe of https://github.com/zaquestion/lab/issues/211 -- I've picked up the changes started there and put up https://github.com/zaquestion/lab/pull/450 It's still not working with subgroups, so I just need to figure that out.

**Comment by zaquestion** [comment] 2020-10-01 17:51
Was able to get this working with #450, it currently depends on a change in `go-gitlab` being merged, once that's in we can bring this in. As mentioned in another issue, the `0.18` release may be a bit, so installing from source may be the best option to get this feature in the nearterm.

**Comment by prarit** [comment] 2020-12-21 12:43
Based on @zaquestion 's response I'm closing this out.

**Closed by prarit** 2020-12-21 12:43 UTC
