### ISSUE TITLE
nil pointer since 0.18.0

### ISSUE THREAD

**Issue by damoon** [zaquestion/lab#562] opened 2021-01-13 20:52 UTC
After updating from 0.17.2 to 0.18.0 creating a merge request triggers a nil pointer.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe85f3a]
goroutine 1 [running]:
github.com/spf13/viper.(*Viper).find(0x0, 0xc000471a60, 0xd, 0x1, 0xc000471a60, 0xd)
	/home/travis/gopath/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1027 +0x3a
github.com/spf13/viper.(*Viper).Get(0x0, 0xc000471a60, 0xd, 0x2, 0x2)
	/home/travis/gopath/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:728 +0x85
github.com/spf13/viper.(*Viper).GetStringSlice(0x0, 0xc000471a60, 0xd, 0x10cc4ed, 0x5, 0xc000471a60)
	/home/travis/gopath/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:865 +0x3f
github.com/zaquestion/lab/cmd.flagConfig.func1(0xc0004c7b80)
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/util.go:45 +0x48b
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc000660700, 0x11c37a0)
	/home/travis/gopath/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x94
github.com/zaquestion/lab/cmd.flagConfig(0xc000660700)
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/util.go:31 +0x37
github.com/zaquestion/lab/cmd.LabPersistentPreRun(0x18c0280, 0xc0006756a0, 0x0, 0x2)
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/util.go:341 +0x39
github.com/spf13/cobra.(*Command).execute(0x18c0280, 0xc000675680, 0x2, 0x2, 0x18c0280, 0xc000675680)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:834 +0x231
github.com/spf13/cobra.(*Command).ExecuteC(0x18bb120, 0xc0000320a0, 0x5, 0x5)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/zaquestion/lab/cmd.Execute()
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/root.go:222 +0x196
main.main()
	/home/travis/gopath/src/github.com/zaquestion/lab/main.go:28 +0x93
```

**Comment by prarit** [comment] 2021-01-13 23:59
@damoon I'm unable to reproduce this.  Were you executing a specific command?

**Comment by aktriver** [comment] 2021-01-15 11:39
I got the same error on Gitlab CI Docker runner (alpine:3.13).

```sh
apk add --update lab
lab --version # 0.18.0

# Git operation

lab mr create --assignee user_id --remove-source-branch --message "Message"
```

In the same job, alpine:3.12(with lab 0.17.2) works fine.

**Comment by prarit** [comment] 2021-01-15 19:19
Odd, it WFM:

[prarit@prarit kernel-test (lab_test)]$ lab mr create --assignee prarit --remove-source-branch --message "Message"
https://gitlab.com/redhat/rhel/kernel/8.y/kernel-test/-/merge_requests/284/diffs
[prarit@prarit kernel-test (lab_test)]$ 

Can you update 'go', rebuild lab, and try again?

**Comment by aktriver** [comment] 2021-01-22 12:58
> Can you update 'go', rebuild lab, and try again?

I used this prebuilt package.
https://pkgs.alpinelinux.org/packages?name=lab&branch=v3.13&repo=community&arch=x86_64

I tried to find a way to reproduce the issue, but I couldn't.
I ran a similar command in three environments.
> `lab mr create --assignee user_id --remove-source-branch --message "Message"`

| environment | lab v0.18.0 |
| --- | --- |
| Local Mac (Homebrew package) | created MR successfully |
| alpine:3.13 on Docker on Local Mac | created MR successfully |
| alpine:3.13 on gitlab docker runner(self hosted) | failed to create MR 🥺 |

The failed Gitlab CI recipe and log is below.

```
mr:
  stage: mr
  image: alpine:latest
  variables:
    LAB_CORE_HOST: ${CI_SERVER_URL}
    LAB_CORE_TOKEN: "______________"
  before_script:
    - apk add --update lab
  script:
    - lab mr create --assignee akutagawa --remove-source-branch --message "Message"
```

```
Running with gitlab-runner 13.2.2 (_______)
   on docker01-runner02 _________
Preparing the "docker" executor
00:03
 Using Docker executor with image alpine:latest ...
 Pulling docker image alpine:latest ...
 Using docker image sha256:7731472c3f2a25edbb9c085c78f42ec71259f2b83485aa60648276d408865839 for alpine:latest ...
Preparing environment
00:01
 Running on runner-mweftymr-project-350-concurrent-0 via 89e5817e9423...
Getting source from Git repository
00:01
 Fetching changes with git depth set to 50...
 Reinitialized existing Git repository in /builds/_____________/.git/
 Checking out f6424286 as mr-test...
 Removing dist/
 Removing node_modules/
 Skipping Git submodules setup
Executing "step_script" stage of the job script
00:03
 $ apk add --update lab
 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
 (1/8) Installing ca-certificates (20191127-r5)
 (2/8) Installing brotli-libs (1.0.9-r3)
 (3/8) Installing nghttp2-libs (1.42.0-r1)
 (4/8) Installing libcurl (7.74.0-r0)
 (5/8) Installing expat (2.2.10-r1)
 (6/8) Installing pcre2 (10.36-r0)
 (7/8) Installing git (2.30.0-r0)
 (8/8) Installing lab (0.18.0-r0)
 Executing busybox-1.32.1-r0.trigger
 Executing ca-certificates-20191127-r5.trigger
 OK: 44 MiB in 22 packages
 $ lab mr create --assignee akutagawa --remove-source-branch --message "Message"
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55b1134f687c]
 goroutine 1 [running]:
 github.com/spf13/viper.(*Viper).find(0x0, 0xc000035540, 0x1d, 0x1, 0x1d, 0x13)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1027 +0x3c
 github.com/spf13/viper.(*Viper).Get(0x0, 0xc000035540, 0x1d, 0xc000035540, 0x1d)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:728 +0x85
 github.com/spf13/viper.(*Viper).GetBool(0x0, 0xc000035540, 0x1d, 0x55b11357e1f4)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:799 +0x45
 github.com/zaquestion/lab/cmd.flagConfig.func1(0xc00044f220)
 	/home/buildozer/aports/community/lab/src/src/github.com/zaquestion/lab/cmd/util.go:39 +0x2e7
 github.com/spf13/pflag.(*FlagSet).VisitAll(0xc0007d3c00, 0x55b113e31a48)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x9f
 github.com/zaquestion/lab/cmd.flagConfig(0xc0007d3c00)
 	/home/buildozer/aports/community/lab/src/src/github.com/zaquestion/lab/cmd/util.go:31 +0x39
 github.com/zaquestion/lab/cmd.LabPersistentPreRun(0x55b114400a40, 0xc00036fe50, 0x0, 0x5)
 	/home/buildozer/aports/community/lab/src/src/github.com/zaquestion/lab/cmd/util.go:341 +0x3b
 github.com/spf13/cobra.(*Command).execute(0x55b114400a40, 0xc00036fe00, 0x5, 0x5, 0x55b114400a40, 0xc00036fe00)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:834 +0x231
 github.com/spf13/cobra.(*Command).ExecuteC(0x55b114401f40, 0xc000030080, 0x8, 0x8)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
 github.com/spf13/cobra.(*Command).Execute(...)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
 github.com/zaquestion/lab/cmd.Execute()
 	/home/buildozer/aports/community/lab/src/src/github.com/zaquestion/lab/cmd/root.go:222 +0x1a5
 main.main()
 	/home/buildozer/aports/community/lab/src/src/github.com/zaquestion/lab/main.go:28 +0x95
 ERROR: Job failed: exit code 2
```

**Comment by damoon** [comment] 2021-01-22 21:56
for me it failed during use within a gitlab job https://gitlab.com/utopia-planitia/exocomp/-/jobs/946240210

**Comment by aktriver** [comment] 2021-01-24 06:06
I was able to reproduce the problem without creating an MR.  
I think this is related to #566.  

```
mr:
  stage: mr
  image: alpine:3.13
  before_script:
    - apk add --update lab # v0.18.0 is installed
  script:
    - lab mr list # fails
    # - lab issue list # fails too
```

**Comment by zaquestion** [comment] 2021-01-24 19:52
@damoon @aktriver I've released `v0.19.0` with the fixes from #566 -- can you confirm if this is still an issue?

**Comment by aktriver** [comment] 2021-01-26 05:02
@zaquestion It still fails ...

> I think this is related to #566.

I'm sorry. My expectation may have been wrong.
This is the minimum `.gitlab-ci.yml` that reproduces the problem.

```yaml
stages:
  - lab

lab:
  stage: lab
  image: alpine:edge
  # variables:
  #   LAB_CORE_HOST: ${CI_SERVER_URL}
  #   LAB_CORE_TOKEN: "TOKEN"
  before_script:
    - apk add --update lab
    - lab version
  script:
    - lab issue list
```

```
$ lab version
 git version 2.30.0
 lab version 0.19.0
 $ lab issue list
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55bc71e24abc]
 goroutine 1 [running]:
 github.com/spf13/viper.(*Viper).find(0x0, 0xc00040e650, 0xe, 0x1, 0xe, 0x3)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:1027 +0x3c
 github.com/spf13/viper.(*Viper).Get(0x0, 0xc00040e650, 0xe, 0xc00040e650, 0xe)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:728 +0x85
 github.com/spf13/viper.(*Viper).GetBool(0x0, 0xc00040e650, 0xe, 0x55bc71e66e2e)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/viper@v1.7.1/viper.go:799 +0x45
 github.com/zaquestion/lab/cmd.flagConfig.func1(0xc00084a320)
 	/home/buildozer/aports/community/lab/src/lab-0.19.0/cmd/util.go:39 +0x2e7
 github.com/spf13/pflag.(*FlagSet).VisitAll(0xc00030f700, 0x55bc72764a48)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x9f
 github.com/zaquestion/lab/cmd.flagConfig(0xc00030f700)
 	/home/buildozer/aports/community/lab/src/lab-0.19.0/cmd/util.go:31 +0x39
 github.com/zaquestion/lab/cmd.LabPersistentPreRun(0x55bc72d3ac40, 0x55bc72d8e530, 0x0, 0x0)
 	/home/buildozer/aports/community/lab/src/lab-0.19.0/cmd/util.go:341 +0x3b
 github.com/spf13/cobra.(*Command).execute(0x55bc72d3ac40, 0x55bc72d8e530, 0x0, 0x0, 0x55bc72d3ac40, 0x55bc72d8e530)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:834 +0x231
 github.com/spf13/cobra.(*Command).ExecuteC(0x55bc72d37fa0, 0xc000030180, 0x3, 0x3)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
 github.com/spf13/cobra.(*Command).Execute(...)
 	/home/buildozer/aports/community/lab/src/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
 github.com/zaquestion/lab/cmd.Execute()
 	/home/buildozer/aports/community/lab/src/lab-0.19.0/cmd/root.go:222 +0x196
 main.main()
 	/home/buildozer/aports/community/lab/src/lab-0.19.0/main.go:28 +0x95
 ERROR: Job failed: exit code 2
```

**Comment by damoon** [comment] 2021-02-17 11:29
i tested 0.19. it still fails.
https://gitlab.com/utopia-planitia/exocomp/-/jobs/1036151417

**Comment by bmeneguele** [comment] 2021-02-17 13:52
That's really odd. I've downloaded both `alpine:edge` and `alpine:3.13` from docker.io and manually installed lab on it:
```
$ podman run --rm -it alpine:edge sh 
# apk add --update lab
```
After, I used the command from one of the comments:

>   before_script:
>     - apk add --update lab
>     - lab version
>   script:
>     - lab issue list
> ```

And it just worked for both images using both `root` and a normal user in a test repo I have in gitlab:
```
$ lab issue list
#2 test 1
#1 test
$ uname -a
Linux 97eca0036534 5.10.11-200.fc33.x86_64 #1 SMP Wed Jan 27 20:21:22 UTC 2021 x86_64 Linux
$ cat /etc/motd
cat /etc/motd
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <http://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.
```

Can it be something somehow related to the CI environment?
Tbh, I have no idea what's going on.

**Comment by soullivaneuh** [comment] 2021-03-04 09:34
@bmeneguele  This bug looks indeed very vicious and looks to be "resolved" by itself, at least for me.

I tried with

`alpine:edge` distributing `0.20`:

```Dockerfile
FROM alpine:edge
RUN apk add --no-cache git~=2 lab~=0.20 jq~=1
```

`alpine:3` distributing `0.18`:

```Dockerfile
FROM alpine:3
RUN apk add --no-cache git~=2 lab~=0.18 jq~=1
```

`alpine:3` distributing `0.20` from `edge/community` (I did have my first issue on this case):

```Dockerfile
FROM alpine:3
RUN echo '@edge/main http://dl-cdn.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories
RUN echo '@edge/community http://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories
RUN echo '@edge/testing http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
RUN apk add --no-cache git~=2 lab@edge/community~=0.20 jq~=1
```

So... I don't know either? :upside_down_face: 

Maybe a fail on the Alpine package build system that is no resolved? :thinking:

**Comment by bmeneguele** [comment] 2021-03-04 13:50
> Maybe a fail on the Alpine package build system that is no resolved? thinking

Maybe :smile: . Thank you very much for checking it @soullivaneuh .
I'm going to close this issue in the hope it was an issue external to the project (golang version in Alpine build system maybe?).
But please, feel free to reopen whenever needed!

**Comment by soullivaneuh** [comment] 2021-03-22 15:48
@bmeneguele Sorry for that, but my comment is falsy.

I tried again with a `mr create` command and got the same failures as above.

It looks to be specific to that command.

**Comment by soullivaneuh** [comment] 2021-03-22 16:02
Here is the related `Dockerfile`:

```Dockerfile
FROM alpine:3.13.2
RUN apk add --no-cache bash \
  coreutils \
  curl \
  gnupg \
  grep \
  httpie \
  jq \
  make \
  openssh-client \
  wget
RUN apk add --no-cache git~=2 lab~=0.18 jq~=1
COPY rootfs /
WORKDIR /app
```

With that, I do have a crash with: 

```
lab merge-request --remove-source-branch --message "${message}"
```

I think you can safely remove the two last ones that are just files addition for my environment.

**Comment by soullivaneuh** [comment] 2021-03-22 16:32
Another breaking case this case with Debian:

```
FROM registry.gitlab.com/nexylan/docker/core:3.1.0-debian
RUN apt-get update && apt-get install --yes --no-install-recommends \
  git=1:2.* \
  jq=1.* \
  && rm --recursive --force /var/lib/apt/lists/*

ENV LAB_VERSION=0.21.0
RUN mkdir extracted \
  && curl -sL "https://github.com/zaquestion/lab/releases/download/v${LAB_VERSION}/lab_${LAB_VERSION}_linux_amd64.tar.gz" | tar -C extracted -xzf - \
  && install -m755 extracted/lab /usr/local/bin/lab \
  && rm -rf extracted
```

Note: If I replace `0.21.0` by `0.17.2`, all is working like a charm.

**Comment by bmeneguele** [comment] 2021-03-29 21:22
Ok, we were able to reproduce the issue, finally! And it's quite "obvious" :facepalm: 
Some distros and CI systems set their user home and config dir for different places...
We're looking into it.

**Comment by prarit** [comment] 2021-03-30 21:16
The information in https://github.com/zaquestion/lab/issues/659 may be useful here.  I can replicate the panic in GitLab's CI.

**Comment by prarit** [comment] 2021-04-29 13:53
Hey everyone, The first commit in https://github.com/zaquestion/lab/pull/670 fixes this panic.

**Closed** 2021-04-29 18:35 UTC
Labels: help wanted
