### ISSUE TITLE
branch not present on remote: origin

### ISSUE THREAD

**Issue by shkm** [zaquestion/lab#57] opened 2017-12-11 07:58 UTC
On branch `issues/35`, pushed to gitlab:

```
> lab merge-request
2017/12/11 08:56:36 aborting MR, branch not present on remote: origin
```

Any ideas?

**Comment by zaquestion** [comment] 2017-12-12 05:43
That should only happen when the branch you're on can't be found on the remote. Can you get me the output of `git remote -v`

You might also try `DEBUG=1 lab merge-request` and seeing what pops out, the debug flag has mixed results w.r.t. being useful

**Comment by zaquestion** [comment] 2017-12-12 06:11
If your branch is pushed on a different remote, use `git push -u <remote> <branch>` to set the upstream for the branch. Lab uses the tracked branch and defaults to the fork remote.

**Comment by zaquestion** [comment] 2018-01-05 04:19
@shkm this was probably caused by https://github.com/xanzy/go-gitlab/issues/233 -- I've put up a fix over there, once its merged I'll update lab with a fix.

**Comment by zaquestion** [comment] 2018-01-07 08:16
Branches with slashes in them should now work in version `0.9.0`

**Closed by zaquestion** 2018-01-07 08:16 UTC
