### ISSUE TITLE
lab mr b doesn't work anymore

### ISSUE THREAD

**Issue by MartinDelille** [zaquestion/lab#271] opened 2018-12-21 14:12 UTC
The `lab mr b` feature opening the current merge request in the browser doesn't work anymore in the latest version (0.14.0).

**Comment by zaquestion** [comment] 2018-12-22 23:30
@MartinDelille This feature was released in `0.14.0` https://github.com/zaquestion/lab/pull/221 -- I just gave it a shot locally and saw the desired behavior. Additionally the test seems to be working as well.

```
$ GO111MODULE=on make test run=Test_mrBrowseWithParameter
ok      github.com/zaquestion/lab/cmd   1.286s  coverage: 10.7% of statements in ./...
```

Let me know what you're seeing and I'll try and help

**Comment by MartinDelille** [comment] 2018-12-23 10:04
Ok sorry I thought I was using the good version but I was still on an old one.

FYI, I tried debugging it my self and had this unrelated error on master:

```
$ make
go build -ldflags "-X \"main.version=v0.14.0-25-gbe24c68\"" github.com/zaquestion/lab
# github.com/zaquestion/lab/internal/gitlab
internal/gitlab/gitlab.go:387:61: undefined: gitlab.Discussion
internal/gitlab/gitlab.go:393:20: undefined: gitlab.Discussion
internal/gitlab/gitlab.go:394:10: undefined: gitlab.ListIssueDiscussionsOptions
internal/gitlab/gitlab.go:402:22: lab.Discussions undefined (type *gitlab.Client has no field or method Discussions)
make: *** [build] Error 2
```

**Comment by zaquestion** [comment] 2018-12-24 20:08
Yeah the make file should probably set modules to on. It's needs to be `GO111MODULE=on make` now

**Comment by MartinDelille** [comment] 2018-12-25 10:12
I could indeed have guess it from the `.travis.yml` file but keeping a simple `make` command make easier for random contributor like me to have quickly a dev environment set up.

**Comment by MartinDelille** [comment] 2019-02-13 15:18
This command fails again with the latest version (`0.15.2`):

$ lab mr browse
panic: interface conversion: interface {} is map[string]interface {}, not []map[string]interface {}

goroutine 1 [running]:
github.com/zaquestion/lab/cmd.glob..func23(0x1a4c8a0, 0x1a74908, 0x0, 0x0)
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/mr_browse.go:28 +0x7be
github.com/spf13/cobra.(*Command).execute(0x1a4c8a0, 0x1a74908, 0x0, 0x0, 0x1a4c8a0, 0x1a74908)
	/home/travis/gopath/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:769 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0x1a4a0a0, 0x1a4c8a0, 0x1a74908, 0xc00022c218)
	/home/travis/gopath/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:855 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x1a4a0a0, 0xc00008c040, 0x2)
	/home/travis/gopath/pkg/mod/github.com/rsteube/cobra@v0.0.1-zsh-completion-custom/command.go:803 +0x2b
github.com/zaquestion/lab/cmd.Execute()
	/home/travis/gopath/src/github.com/zaquestion/lab/cmd/root.go:289 +0x186
main.main()
	/home/travis/gopath/src/github.com/zaquestion/lab/main.go:127 +0x5e
```

**Comment by zaquestion** [comment] 2019-02-21 18:54
Yikes @MartinDelille so sorry for the trouble! And that I'm only just seeing this! From the error looks like a regression in some of the config handling, I'll get a fix out soon.

**Comment by MartinDelille** [comment] 2019-03-17 00:10
I managed to fix it by forcing my gitlab url here: https://github.com/zaquestion/lab/blob/master/cmd/mr_browse.go#L27-L29

**Comment by zaquestion** [comment] 2019-03-17 00:38
Yeah goodness sorry, I've got a fix for it locally I haven't had a chance to push out :shame: -- will try to do that Monday. Tomorrow 3ambharvest then farmers market

**Closed** 2019-03-21 22:43 UTC

**Comment by zaquestion** [comment] 2019-03-21 23:03
@MartinDelille Sorry for the delay, try it out in `0.15.3`

**Comment by MartinDelille** [comment] 2019-03-22 10:25
It works! Thanks!
